name: prokaryotic-wgs-pipeline
channels:
  - bioconda
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - fastqc=0.11.9
  - fastp=0.23.4
  - spades=4.2.0
  - quast=5.2.0
  - busco=5.4.7
  - prokka=1.14.6
  - abricate=1.0.1
  - fastani=1.33

